/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
/**
 *
 * @author Joko Prasetyo Utomo
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rank = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        akhir = new javax.swing.JLabel();
        hitungcfsf = new javax.swing.JLabel();
        hitungGaP = new javax.swing.JLabel();
        nilaiAwal = new javax.swing.JLabel();
        kelas2 = new javax.swing.JLabel();
        guru1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankMouseClicked(evt);
            }
        });
        jPanel1.add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 170, 170));

        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });
        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 180, 180));

        akhir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        akhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akhirMouseClicked(evt);
            }
        });
        jPanel1.add(akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 180, 170));

        hitungcfsf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hitungcfsf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungcfsfMouseClicked(evt);
            }
        });
        jPanel1.add(hitungcfsf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 170, 180));

        hitungGaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hitungGaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungGaPMouseClicked(evt);
            }
        });
        jPanel1.add(hitungGaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 170, 170));

        nilaiAwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nilaiAwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaiAwalMouseClicked(evt);
            }
        });
        jPanel1.add(nilaiAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 180, 180));

        kelas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kelas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelas2MouseClicked(evt);
            }
        });
        jPanel1.add(kelas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 170, 180));

        guru1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guru1MouseClicked(evt);
            }
        });
        jPanel1.add(guru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 180));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/home2.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 1390, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1380, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guru1MouseClicked
        // TODO add your handling code here:
        dataGuru guru=new dataGuru();
        guru.setVisible(true);
    }//GEN-LAST:event_guru1MouseClicked

    private void kelas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelas2MouseClicked
        // TODO add your handling code here:
        dataKelas kelas=new dataKelas();
        kelas.setVisible(true);
    }//GEN-LAST:event_kelas2MouseClicked

    private void nilaiAwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaiAwalMouseClicked
        // TODO add your handling code here:
        hitungAwal awal=new hitungAwal();
        awal.setVisible(true);
    }//GEN-LAST:event_nilaiAwalMouseClicked

    private void hitungGaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungGaPMouseClicked
         // TODO add your handling code here:
        gapkonvert gap=new gapkonvert();
        gap.setVisible(true);
    }//GEN-LAST:event_hitungGaPMouseClicked

    private void hitungcfsfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungcfsfMouseClicked
        // TODO add your handling code here:
        hitungCFSF cfsf=new hitungCFSF();
        cfsf.setVisible(true);
    }//GEN-LAST:event_hitungcfsfMouseClicked

    private void akhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akhirMouseClicked
        // TODO add your handling code here:
        menuHasil end=new menuHasil();
        end.setVisible(true);
    }//GEN-LAST:event_akhirMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        // TODO add your handling code here:
        laporan rp=new laporan();
        rp.setVisible(true);
    }//GEN-LAST:event_reportMouseClicked

    private void rankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankMouseClicked
        // TODO add your handling code here:
        ranking rk=new ranking();
        rk.setVisible(true);
    }//GEN-LAST:event_rankMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akhir;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel guru1;
    private javax.swing.JLabel hitungGaP;
    private javax.swing.JLabel hitungcfsf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kelas2;
    private javax.swing.JLabel nilaiAwal;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel report;
    // End of variables declaration//GEN-END:variables
}
